# Generated by Django 3.2.9 on 2021-11-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.FileField(default='media/default.png', upload_to='media/images/'),
        ),
    ]
