# Generated by Django 3.2.9 on 2021-12-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_logo',
            field=models.FileField(default='media/default.png', upload_to='media/images/'),
        ),
    ]
