# Generated by Django 3.2.9 on 2021-12-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_client_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_cover',
            field=models.FileField(default='media/bgcover.jpg', upload_to='media/images/'),
        ),
    ]
