# Generated by Django 3.2.9 on 2021-12-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_company_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_emp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='company_established',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
