# Generated by Django 3.2.9 on 2021-12-10 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='emp_requirement',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_salary',
            field=models.ImageField(upload_to=''),
        ),
    ]
