# Generated by Django 3.2.9 on 2021-12-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20211210_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_cover',
            field=models.FileField(default='media/company-default-cover-pic.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_cover',
            field=models.FileField(default='media/company-default-cover-pic.jpg', upload_to='media/images/'),
        ),
    ]
