# Generated by Django 3.2.9 on 2021-12-15 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_skills',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
