# Generated by Django 3.2.9 on 2021-12-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_companyfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
