# Generated by Django 3.2.9 on 2021-12-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_jobpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_skills',
            field=models.TextField(max_length=100),
        ),
    ]
