# Generated by Django 3.2.9 on 2021-12-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_alter_client_client_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_skills',
            field=models.CharField(max_length=50),
        ),
    ]
