# Generated by Django 3.2.9 on 2021-12-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_client_client_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.client')),
            ],
        ),
    ]
